### ISSUE TITLE
Change test runner to use useEnv instead of ignoreEnv

### ISSUE THREAD

**Issue by bitemyapp** [yesodweb/yesod-scaffold#56]
https://github.com/yesodweb/yesod/issues/908#issuecomment-69805178

@MaxGabriel

**Comment by snoyberg** [comment]
I think this is the right decision. Especially given the recent move to automatically wipe out the entire database in the test suite, I wouldn't want an environment variable I set during development to be used during testing.

**Comment by amitaibu** [comment]
I'll open another issue if needed, but this the same issue, and it threw my off as-well, because of the followings comments snippets:

* config/settings.yml: `# See config/test-settings.yml for an override during tests`
* config/test-settings.yml: `#By design, this setting prevents the MYSQL_DATABASE environment variable, from affecting test runs ...`

So reading both comments made me _think_ variables could be overriden. I believe the concern of wiping production databases is no longer there given we hardcode the `database` name in the `test-settings.yml`

**Comment by snoyberg** [comment]
I think you're right. Wanna send a PR?

**Comment by amitaibu** [comment]
Sure, I'll try to follow the README steps..

**Comment by amitaibu** [comment]
Oh, actually I think it's just creating the PR without all the build process. Couple of minutes :)
